### ISSUE TITLE
MAgent2's Development Roadmap

### ISSUE THREAD

**Issue by mwydmuch** [Farama-Foundation/MAgent2#41]
This is a loose roadmap of our plans for the further development of MAgent2.

**Items marked as (help wanted) can be picked up by volunteers earlier.**
If you would like to contribute join our discord server https://discord.gg/bnJ6kubTg6 and put a message in the new contributes channel with any particular topics that you would like to work.

Early August 2024:
- [x] Fix misc issues with installation
- [x] Add Python 3.11 support
- [ ] 0.3.3 maintenance release

Late August/Early September 2024:
- [ ] Add official support for numpy 2.0+
- [ ] Update wheels building to support ARM and macOS wheels
- [ ] 0.3.4 maintenance release
